package Webboxes::Controller::Root;
use Moose;
use namespace::autoclean;

BEGIN { extends 'Catalyst::Controller' }

#
# Sets the actions in this controller to be registered with no prefix
# so they function identically to actions created in MyApp.pm
#
__PACKAGE__->config(namespace => '');

=head1 NAME

Webboxes::Controller::Root - Root Controller for Webboxes

=head1 DESCRIPTION

[enter your description here]

=head1 METHODS

=head2 index

The root page (/)

=cut

sub index :Path :Args(0) {
    my ( $self, $c ) = @_;

    # Hello World
    $c->response->body( $c->welcome_message );
}

=head2 yui

A page generated by Catalyst::Helper::View::TT::Bootstrap::YUI

=cut

sub yui :Global {
    my ( $self, $c ) = @_;

    # Hello World
    $c->stash(template => 'site/html.tt' );
}

=head2 color

Display a list of colors

=cut

sub color :Global {
  my($self,$c) = @_;

  $c->stash->{template} = 'color.tt';
  $c->stash->{colors} = [$c->model('Color')->colors()];
}

=head2 default

Standard 404 error page

=cut

sub default :Path {
    my ( $self, $c ) = @_;
    $c->response->body( 'Page not found' );
    $c->response->status(404);
}

=head2 end

Attempt to render a view, if needed.

=cut

sub end : ActionClass('RenderView') {}

=head1 AUTHOR

Soren Dossing

=head1 LICENSE

This library is free software. You can redistribute it and/or modify
it under the same terms as Perl itself.

=cut

__PACKAGE__->meta->make_immutable;

1;
